stages:
- build
- startdev
- deploy

build:
  stage: build
  script:
  - "docker build -t data-server:master -t data-server:$CI_COMMIT_SHA ."

startdev:
  stage: startdev
  script:
  - "docker stop data-server-dev || true"
  - "docker rm data-server-dev || true"
  - "docker run -p 8000:8000 --restart unless-stopped -v DataStorageDev:/app/storage:ro --name data-server-dev -d data-server:master"
  
deploy:
  stage: deploy
  when: manual
  script:
  - "docker stop data-server || true"
  - "docker rm data-server || true"
  - "docker run -p 80:8000 --restart unless-stopped -v DataStorage:/app/storage:ro --name data-server -d data-server:master"